### ISSUE TITLE
unmask phage variants in variant matrix code files

### ISSUE THREAD

**Issue by zenalapp** [alipirani88/snpkit#10]
Change masked phage variants (-2's) to whatever the actual variant call is.

Then when we update the numbers, we can have -2 be filtered variants (the old 2).

Specific files:
SNP_mat_code
Indel_mat_code

**Comment by alipirani88** [comment]
Note: Keep Phage region masked in alignments.

**Comment by alipirani88** [comment]
Opening this issue again.
Major bug introduced while incorporating status code changes.
Less priority and will restart working on after finishing the inclusion of outgroup functionality.
