### ISSUE TITLE
Rewrite gubbins_env.yml file 

### ISSUE THREAD

**Issue by kylegontjes** [alipirani88/snpkit#55]
Add pandas to the gubbins environment https://github.com/nickjcroucher/gubbins/blob/master/environment.yml for phase 2 gubbins run

**Comment by alipirani88** [comment]
@kylegontjes Moving forward - we will be using the official gubbins environment yml file. I have added the necessary pandas libraries to this yml file - https://github.com/alipirani88/snpkit/blob/master/envs/environment_gubbins.yml
