### ISSUE TITLE
Reference genome file requirements

### ISSUE THREAD

**Issue by kylegontjes** [alipirani88/snpkit#59]
What file is needed for the reference genome's annotation file? 

Does the extension need to be .gbf or can it be .gbk? 

If a .gbf file extension is required, ensure that notation is provided in the wiki and/or README file.

**Comment by kylegontjes** [comment]
If my memory serves me correctly, default prokka outputs only .gbk files and not .gbf. It'd be good to note that the .gbf and .gbk files are essentially the same and a quick copy of the file could solve the possible extension requirement issue.

**Comment by alipirani88** [comment]
I have added the reference genome extension requirement and the required reference genome specific files to run snpkit. I am closing this ticket.
