### ISSUE TITLE
variant matrix code numbers

### ISSUE THREAD

**Issue by katiesaund** [alipirani88/snpkit#9]
it's confusing that some "bad" sites (filtered) are positive numbers (2) and the rest are negative. Can we make this number schema more meaningful? To discuss with @alipirani88 @zmml

**Comment by alipirani88** [comment]
I will move 2(filtered) and 3(true but filtered because of 2) to -5 and -6 resp.

**Comment by zmml** [comment]
@alipirani88 I think we should keep 3 as a positive number. @katiesaund do you agree?

**Comment by alipirani88** [comment]
yeah, makes sense.

**Comment by alipirani88** [comment]
Opening this issue again.
Major bug introduced while incorporating status code changes.
Less priority and will restart working on after finishing the inclusion of outgroup functionality.
